package com.good.login;
import com.good.g_import.Manager_import;
import com.good.employee.Manager_set_get;
import com.good.sale.manage.FrmManager;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class NewJFrame extends javax.swing.JFrame {


     public NewJFrame() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIdentity = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLog_in = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtAccount = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jButton2.setText("jButton2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("经理登录界面");
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        btnLog_in.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        btnLog_in.setText("登录");
        btnLog_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog_inActionPerformed(evt);
            }
        });
        getContentPane().add(btnLog_in);
        btnLog_in.setBounds(40, 171, 88, 35);

        btnCancel.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        btnCancel.setText("退出");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(224, 171, 91, 35);

        lblPassword.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        lblPassword.setText("密码");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(50, 130, 48, 34);

        lblAccount.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        lblAccount.setText("帐号");
        getContentPane().add(lblAccount);
        lblAccount.setBounds(50, 70, 48, 34);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(120, 130, 170, 30);

        txtAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountActionPerformed(evt);
            }
        });
        getContentPane().add(txtAccount);
        txtAccount.setBounds(120, 70, 170, 30);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/good/login/未标题-1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountActionPerformed
        
    }//GEN-LAST:event_txtAccountActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
         if(JOptionPane.showConfirmDialog(null,"您要退出本系统，确定吗？","退出系统",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)==JOptionPane.YES_OPTION){
            System.out.println((new Date()).toString()+"退出系统");
            System.exit(0);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLog_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog_inActionPerformed
        String eNO = txtAccount.getText();
        String password = txtPassword.getText();
        Manager_import  mimport = new Manager_import();
        Manager_set_get man = mimport.findByid(eNO);
        if(man==null){
            System.out.println("用户名不存在");
            JOptionPane.showMessageDialog(null, "用户名不存在，请重新输入", "警告",JOptionPane.ERROR_MESSAGE);
        }else{
            if(!man.getCode().equals(password)){
                System.out.println("密码不正确");
                JOptionPane.showMessageDialog(null, "密码不正确，请重新输入", "警告",JOptionPane.ERROR_MESSAGE);
            }else{
                System.out.println("密码正确");
                FrmManager frame=new FrmManager();
                frame.setSize(444,290);
                this.setVisible(false);
                Dimension winSize = Toolkit.getDefaultToolkit().getScreenSize(); //屏幕分辨率
                frame.setLocation((winSize.width - frame.getWidth()) / 2, (winSize.height - frame.getHeight()) / 2); //窗口定位 
                frame.setLocationRelativeTo(null);//窗口在屏幕中间显示 
                frame.setVisible(true);
                this.dispose();
            }
        }
                
               
            

    }//GEN-LAST:event_btnLog_inActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame frame = new NewJFrame();             
                                   
                frame.setVisible(true);//显示窗口               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnIdentity;
    private javax.swing.JButton btnLog_in;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
