/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.good.sale.manage;

import com.good.DBcon.MyDBCon;
import java.util.Vector;

public class FrmSalesman extends javax.swing.JFrame {
     Vector data;
     Vector title;
     int row=0;
    public FrmSalesman() {
        initComponents();
        data=MyDBCon.queryVectorData1("Select * from Salesman");
        showTextData2(row);
        lock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnPerson_info = new javax.swing.JButton();
        lblNO = new javax.swing.JLabel();
        lblSales_name = new javax.swing.JLabel();
        txtSales_name = new javax.swing.JTextField();
        txtNO = new javax.swing.JTextField();
        btnSales_record = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setLabel("销售员管理");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("销售员界面");
        getContentPane().setLayout(null);

        btnPerson_info.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        btnPerson_info.setText("个人信息");
        btnPerson_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerson_infoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPerson_info);
        btnPerson_info.setBounds(28, 207, 143, 35);

        lblNO.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        lblNO.setText("编号");
        getContentPane().add(lblNO);
        lblNO.setBounds(57, 138, 48, 27);

        lblSales_name.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        lblSales_name.setText("姓名");
        getContentPane().add(lblSales_name);
        lblSales_name.setBounds(57, 59, 48, 27);

        txtSales_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSales_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txtSales_name);
        txtSales_name.setBounds(154, 61, 171, 27);

        txtNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOActionPerformed(evt);
            }
        });
        getContentPane().add(txtNO);
        txtNO.setBounds(154, 140, 171, 27);

        btnSales_record.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        btnSales_record.setText("销售记录");
        btnSales_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSales_recordActionPerformed(evt);
            }
        });
        getContentPane().add(btnSales_record);
        btnSales_record.setBounds(231, 207, 140, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/good/sale/manage/2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerson_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerson_infoActionPerformed

         FrmPerInfo1 frame=new FrmPerInfo1();
         frame.setSize(432,340);
         frame.setLocationRelativeTo(null);//窗口在屏幕中间显示
         frame.setVisible(true);  
         this.dispose();
         //关闭当前窗体
    }//GEN-LAST:event_btnPerson_infoActionPerformed

    private void txtNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOActionPerformed
         FrmSaleRecord frame=new FrmSaleRecord();
         frame.setSize(650,400);
         frame.setVisible(true);
         //关闭当前窗体
    }//GEN-LAST:event_txtNOActionPerformed

    private void btnSales_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSales_recordActionPerformed
         FrmSaleRecord frame=new FrmSaleRecord();
         frame.setSize(650,488);
         frame.setVisible(true);
         this.dispose();
         //关闭当前窗体
    }//GEN-LAST:event_btnSales_recordActionPerformed

    private void txtSales_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSales_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSales_nameActionPerformed

    public void showTextData2(int index){
        Vector line=(Vector)data.get(index);
        txtNO.setText(line.get(0).toString());
        txtSales_name.setText(line.get(1).toString());
    }
     //加锁
    public void lock(){
        txtNO.setEnabled(false);
        txtSales_name.setEnabled(false);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSalesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSalesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSalesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSalesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSalesman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerson_info;
    private javax.swing.JButton btnSales_record;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNO;
    private javax.swing.JLabel lblSales_name;
    private javax.swing.JTextField txtNO;
    private javax.swing.JTextField txtSales_name;
    // End of variables declaration//GEN-END:variables
}
