/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.good.sale.manage;

import com.good.DBcon.MyDBCon;
import java.awt.Rectangle;
import java.util.*;
import javax.swing.*;//JOptionPane的导包
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 随缘
 */
public class FrmSaleRecord extends javax.swing.JFrame {
    Vector data;
    int row = 0;//下标
    Vector title;//在下面实例化
     //表格模式
    DefaultTableModel dtm=new DefaultTableModel();//帮助掌控表格中的数据
    //带滚动条的面板
    JScrollPane scp=new JScrollPane();
    //表格
    JTable tbl=new JTable(dtm);//要先有DefaultTableModel dtm=new DefaultTableModel();把表格模式放入表格作为构造方法的参数
    
   
    public FrmSaleRecord() {
        initComponents();
        btnReset.setVisible(false);
        data=MyDBCon.queryVectorData2("Select * from sell");
        getTextData(row);
        setLocationRelativeTo(null);
        title = new Vector();//实例化title
        //准备表头的内容
        title.add("商品编号");
        title.add("商品名称");
        title.add("销售数量");
        title.add("库存");
        title.add("单价");
        title.add("总价");
        title.add("处理人");
        title.add("销售日期");
        title.add("顾客");
        title.add("单号");
        
        
        
        //放置表格到滚动面板上
        scp.setViewportView(tbl);
        //设置滚动面板位置和大小
        scp.setBounds(new Rectangle(5,333,555,300));//一开始是因为数据少，所以没有显示出滚动条
        //将滚动面板放置在窗体的内容面板上
        this.getContentPane().add(scp);
        showTableData();//调用显示表格数据的方法
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {//添加鼠标点击监听器
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //根据二维的Vector，在文本框中显示数据的方法,
     public void getTextData(int index){
         Vector line=(Vector)data.get(index);//因为获得的是一个个vector对象，所以用(vector)强制性转换
         txtGno.setText(line.get(0).toString());//get(0)是line的第一个字段
         txtGname.setText(line.get(1).toString());
         txtSno.setText(line.get(2).toString());
         txtInv.setText(line.get(3).toString());//库存
         txtPrice.setText(line.get(4).toString());
         txtSprice.setText(line.get(5).toString());//总价
         txtNO.setText(line.get(6).toString());
         txtEman.setText(line.get(7).toString());
         txtDate.setText(line.get(8).toString());
         txtCname.setText(line.get(9).toString());
         txtRno.setText(line.get(10).toString());
         //文本框一显示数据则加锁,表示显示数据时不容许修改
         lock();//但是下面操作按钮不锁
     }
     public void showTableData(){
        //利用表格模式显示数据
        dtm.setDataVector(data, title);
    } 
    
    //加锁的方法,文本,按钮不允许操作
    public void lock(){
        txtGno.setEnabled(false);//该文本框设置为是否可用
        txtGname.setEnabled(false);
        txtSno.setEnabled(false);
        txtInv.setEnabled(false);
        txtPrice.setEnabled(false);
        txtSprice.setEnabled(false);
        txtEman.setEnabled(false);
        txtDate.setEnabled(false);
        txtCname.setEnabled(false);
        txtNO.setEnabled(false);
        txtRno.setEnabled(false);
        btnRecord.setEnabled(true);
        btnQuary.setEnabled(true);
        btnSave.setEnabled(false);//保存，取消为关闭状态
        btnCancle.setEnabled(false);
        btnReset.setEnabled(false);
    }
    //解锁的方法1-记录用
    public void unlock(){
        txtGno.setEnabled(true);//该文本框设置为是否可用
        txtGname.setEnabled(true);
        txtSno.setEnabled(true);
        txtInv.setEnabled(true);
        txtPrice.setEnabled(true);
        txtSprice.setEnabled(true);
        txtEman.setEnabled(true);
        txtDate.setEnabled(true);
        txtCname.setEnabled(true);
        txtRno.setEnabled(true);
        txtNO.setEnabled(true);
        btnRecord.setEnabled(false);
        btnQuary.setEnabled(false);
        btnSave.setEnabled(true);//保存，取消为关闭状态
        btnCancle.setEnabled(true);
        btnReset.setEnabled(true);
    }
    //解锁的方法1-查询用
     public void unlock2(){
        txtGno.setEnabled(true);//该文本框设置为是否可用
        txtGname.setEnabled(true);
        txtSno.setEnabled(false);
        txtInv.setEnabled(false);
        txtPrice.setEnabled(false);
        txtSprice.setEnabled(false);
        txtNO.setEnabled(false);
        txtEman.setEnabled(true);
        txtDate.setEnabled(true);
        txtCname.setEnabled(true);
        txtRno.setEnabled(false);
        btnRecord.setEnabled(false);
        btnQuary.setEnabled(true);
        btnSave.setEnabled(false);//保存，取消为关闭状态
        btnCancle.setEnabled(true);
        btnReset.setEnabled(true);
     }
    //清空文本框的方法
    public void clearText(){
        txtGno.setText("");
        txtGname.setText("");
        txtSno.setText("");
        txtInv.setText("");
        txtPrice.setText("");
        txtSprice.setText("");
        txtEman.setText("");
        txtDate.setText("");
        txtCname.setText("");
        txtRno.setText("");
        txtNO.setText("");
    }
    //表格点击事件处理方法
    public void tblClicked(java.awt.event.MouseEvent evt){
        row=tbl.getSelectedRow();//tbl获得当前选中行的方法getSelectedRow()
        getTextData(row);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGno = new javax.swing.JTextField();
        txtGname = new javax.swing.JTextField();
        txtSno = new javax.swing.JTextField();
        txtInv = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtSprice = new javax.swing.JTextField();
        btnRecord = new javax.swing.JButton();
        btnQuary = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtEman = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRno = new javax.swing.JTextField();
        btnCancle = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        lblNO = new javax.swing.JLabel();
        txtNO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("销售管理");

        jLabel2.setText("商品编号");

        jLabel3.setText("商品名");

        jLabel4.setText("销售数量");

        jLabel5.setText("现有库存");

        jLabel6.setText("单件价格");

        jLabel7.setText("销售总价");

        btnRecord.setText("记录");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        btnQuary.setText("查询");
        btnQuary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaryActionPerformed(evt);
            }
        });

        btnSave.setText("保存");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("重置");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel8.setText("处理人");

        jLabel9.setText("处理日期");

        jLabel10.setText("顾客");

        txtCname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnameActionPerformed(evt);
            }
        });

        jLabel11.setText("记录编号");

        btnCancle.setText("取消");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });

        btnReturn.setText("返回");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        lblNO.setText("处理人编号");

        txtNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblNO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNO, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEman, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSprice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtRno))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuary, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnSave)
                        .addGap(31, 31, 31)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnReset)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtGno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtSno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtRno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNO)
                    .addComponent(txtNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuary)
                    .addComponent(btnSave)
                    .addComponent(btnReturn)
                    .addComponent(btnReset)
                    .addComponent(btnCancle)
                    .addComponent(btnRecord))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//记录
    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        unlock();//按添加时先解锁
        clearText();//清空文本框
        btnReset.setVisible(true);//写到一半可清空
    }//GEN-LAST:event_btnRecordActionPerformed
//保存
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         //获得输入的新数据
        String gNo=txtGno.getText();
        String gName=txtGname.getText();
        String sNo=txtSno.getText();
        String amount=txtInv.getText();
        String sPrice=txtPrice.getText();
        String sumPrice=txtSprice.getText();
        String eName=txtEman.getText();
        String eNo=txtNO.getText();
        String sDate=txtDate.getText();
        String cName=txtCname.getText();
        txtRno.setText((txtRno.getText()+1).toString());
        String recordNo=txtRno.getText();     
        String sql="";
        sql="insert into sell values('"+gNo+"','"+gName+"',"+sNo+","+amount+",'"+sPrice+"','"+sumPrice+"','"+eNo+"','"+eName+"','"+sDate+"','"+cName+"',"+recordNo+")";
                               
        System.out.println(sql);//看看输入的sql格式是否正确
        //保存到表中
        if(MyDBCon.updateData(sql)){//跟数据库打交道，要到MyDBCon中去写//更新成功就返回true
            

            //成功的话弹出对话框告诉用户成功
            JOptionPane.showMessageDialog(null,"保存数据成功","系统提示",JOptionPane.INFORMATION_MESSAGE);//提示对话框
        }else{
            JOptionPane.showMessageDialog(null,"保存数据失败","系统提示",JOptionPane.ERROR_MESSAGE);//错误对话框
        }
        lock();//重新锁上
        btnReset.setVisible(false);//:
    }//GEN-LAST:event_btnSaveActionPerformed
//重置
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearText();
    }//GEN-LAST:event_btnResetActionPerformed
//取消
    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        getTextData(row);//当点了修改按钮后取消，即重新显示数据即可
        btnReset.setVisible(false);
    }//GEN-LAST:event_btnCancleActionPerformed
//查询
    private void btnQuaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaryActionPerformed
        //解锁2
        unlock2();
        //获得用户给的条件
        String gNo=txtGno.getText();
        String gName=txtGname.getText();
        //String sNo=txtSno.getText();
        //String amount=txtInv.getText();
        //String sPrice=txtPrice.getText();
        //String sumPrice=txtSprice.getText();
        String eName=txtEman.getText();
        String sDate=txtDate.getText();
        //String cName=txtCname.getText();
        //String recordNo=txtRno.getText();     

        //写先写简单的获取全部的sql语句，
        String sql="Select * from sell";
        //再加判断条件
        String query="";//原来的sql语句,下面是各个查询条件
        //商品编号的条件
        if(gNo.length()>0){//大于零则说明用户输入了条件
            query="BorrowID like '%"+gNo+"%'";
        }//作为第一个条件，故无else的情况
        //商品名的条件
        if(gName.length()>0){
            if(query.length()>0)
                query=query+ "and gName like '%"+gName+"%'";
            else//等于零不用拼接，表示是第一个条件
                query="gName like '%"+gName+"%'";
        }
        
        //处理人的条件
        if(eName.length()>0){
            if(query.length()>0)
                query=query+ "and eName like '%"+eName+"%'";
            else
                query="eName like '%"+eName+"%'";
        }//记录日期日期条件
        if(sDate.length()>0){
            if(query.length()>0)
                query=query+ "and sDate like '%"+sDate+"%'";
            else
                query="sDate like '%"+sDate+"%'";
        }
        
        //形成最终的SQL语句
        if(query.length()>0){//即最终的查询条件长度大于0，说明用户有输入条件
            sql=sql+" where "+query;
        }//等于零相当于查询所有，即一开始写的String sql="Select * from Borrow";即没有查询条件
        System.out.println(sql);
        //执行查询
        data=MyDBCon.queryVectorData2(sql);//调用MyDBC里查询的方法,因为是表格显示数据，所以一定要用二维的显示数据的方法
        //在表格中显示数据
        dtm.setDataVector(data, title);//默认的表格模式再次设置数据和表头
    }//GEN-LAST:event_btnQuaryActionPerformed

    private void txtNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOActionPerformed
       
    }//GEN-LAST:event_txtNOActionPerformed

    private void txtCnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnameActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
         FrmSalesman frame=new FrmSalesman();
         frame.setSize(444,300);
         frame.setVisible(true);
         frame.setLocationRelativeTo(null);//窗口在屏幕中间显示 
         this.dispose();
         //关闭当前窗体
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSaleRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSaleRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSaleRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSaleRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSaleRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnQuary;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNO;
    private javax.swing.JTextField txtCname;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEman;
    private javax.swing.JTextField txtGname;
    private javax.swing.JTextField txtGno;
    private javax.swing.JTextField txtInv;
    private javax.swing.JTextField txtNO;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRno;
    private javax.swing.JTextField txtSno;
    private javax.swing.JTextField txtSprice;
    // End of variables declaration//GEN-END:variables
}
